### ISSUE TITLE
NegativeArraySizeException after repeated calls to chat function

### ISSUE THREAD

**Issue by oliverhummel** [ollama4j/ollama4j#61]
With the following code, where I repeatedly call the chat function with an initial ChatResult (for the prompt where I tell the model that I want text translated), I get a NegativeArraySizeException:

```
builder = OllamaChatRequestBuilder.getInstance(model);
OllamaChatRequest requestModel = builder.withMessage(OllamaChatMessageRole.USER, prompt).build();
initialChatResult = ollamaAPI.chat(requestModel);
// ...
// in a loop:
OllamaChatRequest requestModel = 
   builder.withMessages(initialChatResult.getChatHistory()).withMessage(OllamaChatMessageRole.USER, text).build();
OllamaChatResult chatResult = ollamaAPI.chat(requestModel);   // this is where the exception gets thrown
```
Maybe, this is caused by some kind of internal int overflow? 

The negative number keeps (see exception) changing every time. I use ollama 0.3.2 with llama3.1:70b. It happens at around the 20th call.

Here comes the exception:
Exception in thread "main" java.lang.NegativeArraySizeException: -1854670873
	at java.base/java.lang.String.encodeUTF8_UTF16(String.java:1326)
	at java.base/java.lang.String.encodeUTF8(String.java:1299)
	at java.base/java.lang.String.encode(String.java:867)
	at java.base/java.lang.String.getBytes(String.java:1818)
	at java.net.http/jdk.internal.net.http.RequestPublishers$StringPublisher.<init>(RequestPublishers.java:211)
	at java.net.http/java.net.http.HttpRequest$BodyPublishers.ofString(HttpRequest.java:666)
	at java.net.http/java.net.http.HttpRequest$BodyPublishers.ofString(HttpRequest.java:654)
	at io.github.ollama4j.utils.OllamaRequestBody.getBodyPublisher(OllamaRequestBody.java:22)
	at io.github.ollama4j.models.request.OllamaEndpointCaller.callSync(OllamaEndpointCaller.java:65)
	at io.github.ollama4j.OllamaAPI.chat(OllamaAPI.java:588)
	at io.github.ollama4j.OllamaAPI.chat(OllamaAPI.java:566)
	at ollama.MyOllamaApi.translate(MyOllamaApi.java:33)

**Comment by amithkoujalgi** [comment]
Thanks for reporting the issue. It has been fixed now and the fix is available in version [1.0.82](https://github.com/ollama4j/ollama4j/releases/tag/1.0.82). 

For managing long conversations with the model, you can use the following code as a reference:

```java
public class Main {

    public static void main(String[] args) {

        OllamaAPI ollamaAPI = new OllamaAPI();
        ollamaAPI.setRequestTimeoutSeconds(60);

        OllamaChatRequestBuilder builder = OllamaChatRequestBuilder.getInstance("<your-model>");

        // Start with an initial message
        OllamaChatRequest requestModel = builder.withMessage(OllamaChatMessageRole.USER, "<your-first-message>").build();
        OllamaChatResult initialChatResult = ollamaAPI.chat(requestModel);
        System.out.println(initialChatResult.getResponse());

        // Setup conversation history
        List<OllamaChatMessage> history = initialChatResult.getChatHistory();

        // Continue the conversation
        while (true) {
            OllamaChatResult chatResult = ollamaAPI.chat(builder.withMessages(history).withMessage(OllamaChatMessageRole.USER, "<your-new-message>").build());
            System.out.println(chatResult.getResponse());

            // update your conversation history
            history = chatResult.getChatHistory();
        }
    }
}

```

PS: Please force pull/download the dependency.

**Comment by oliverhummel** [comment]
@amithkoujalgi thanks a lot for the really quick fix, everything works in a stable fashion now. 

Also thank you for the pointer to the reference code. The underlying thought of my approach was to not always submit the whole history as this might decrease performance given the fact that it is always growing? Do you have any experience in this regard?

**Comment by amithkoujalgi** [comment]
@oliverhummel Thanks! Glad it works well for you. 
About the history, I do not have much experience of it but what I have observed is that even ChatGPT or any other service allow only limited number of messages in the conversation history and after it reaches a limit it asks you to start a new conversation. So I think it is a general practice to limit conversation history to a certain size.
