### ISSUE TITLE
ReadMe content not correct

### ISSUE THREAD

**Issue by liebki** [ollama4j/ollama4j#68]
Hi guys, I'm the one who created the Minecraft plugin (spigot) "ollama-translator" which uses your library in order to access ollama and translate messages.

In the ReadMe there is another project/reddit link listed but I don't have anything to do with it. Maybe rename "ollama-translator" as head-point to "Minecraft" or something else, I solely did the Minecraft plugin not the mod on Reddit.

Thanks 👏🏻

**Comment by amithkoujalgi** [comment]
Thanks for the information @liebki. Please feel free to correct it and create a PR.

**Comment by amithkoujalgi** [comment]
I hope [this](https://github.com/ollama4j/ollama4j/commit/18760250eaf6f99b60f8d8e8a8b3336504db9bac) adds a distinction.

**Comment by liebki** [comment]
@amithkoujalgi superb 👏🏻
