### ISSUE TITLE
How can I set options when using chat()?

### ISSUE THREAD

**Issue by michaelwechner** [ollama4j/ollama4j#70]
I have used so far

OllamaResult result = ollamaAPI.generate(model, "Some content", false, options);

but upgraded today to Ollama4j  1.0.84 in order to send multiple messages, so I am now using

OllamaResult result = ollamaAPI.chat(chatRequest);

whereas I would also like to set options, but it is not clear to me how I can do this from the Javadocs

https://ollama4j.github.io/ollama4j/apidocs/io/github/ollama4j/OllamaAPI.html

Is this possible somehow?

Thanks

Michael

**Comment by daguava** [comment]
Options can be set when constructing the chat request
Below example is in Kotlin instead of Java, but should give you the idea:
```
 val chatResponse =
        OllamaChatRequestBuilder
            .getInstance(model)
            .withMessage(OllamaChatMessageRole.USER, "this is my message")
            .withOptions(OptionsBuilder()
                .setNumCtx(1024)
                .setTemperature(1.5F)
                .build())
            .build()
```

**Comment by michaelwechner** [comment]
Thank you very much @daguava!

In Java I did it as follows

OllamaChatRequestBuilder builder = OllamaChatRequestBuilder.getInstance("my-model");
OllamaChatRequest chatRequest = builder.withMessage(OllamaChatMessageRole.USER, "this is my first message").build();
...
chatRequest = builder.withMessages(chatRequest.getMessages()).withOptions(options).build();
