### ISSUE TITLE
Support roles "tool" and "function"

### ISSUE THREAD

**Issue by michaelwechner** [ollama4j/ollama4j#71]
If I understand correctly Ollama4j currently supports the following roles

- system
- user
- assistant

whereas Mistral for example also has a role "tool", see https://docs.mistral.ai/api/

Or OpenAI has additionally the role "function", see https://platform.openai.com/docs/api-reference/chat/create whereas "function" got deprecated, but OpenAI also has the role "tool".

Would it make sense to introduce OllamaChatMessageRole.TOOL ?

**Comment by supertick** [comment]
I need it as well.   However, I would suggest a more flexible approach for handling roles. The current implementation uses an enum, which requires continual maintenance as more models introduce new roles.

Proposed Changes:
Dynamic Role Handling:

Instead of using an enum to enforce role values use a string. The role represents a superset of all roles across all models. A String will prevent the need for manual updates every time new roles are introduced.
The enum could still be retained as a reference or guide for commonly used roles, but it should not be enforced strictly.

Also Timestamp in OllamaChatMessage:

The OllamaChatMessage structure should include a timestamp field. This will help models that rely on message history to determine the last or current message from the user, ensuring context is maintained across interactions.

**Comment by michaelwechner** [comment]
What about replacing the enum by static final Strings, similar to

https://github.com/ollama4j/ollama4j/blob/main/src/main/java/io/github/ollama4j/types/OllamaModelType.java

**Comment by amithkoujalgi** [comment]
Hi @michaelwechner. The "tool" role has been added by @daguava and can now be utilized as `OllamaChatMessageRole.TOOL`.

Regarding the suggestion to replace the enum with static final Strings, I believe the variations in roles will be limited, while model types are likely to change more frequently. Therefore, I think it's more sensible to keep `OllamaChatMessageRole` as an enum and update the roles as new ones are introduced.

On the other hand, supporting the option to freely specify model names (if the model isn't available in OllamaModelType) would give users greater flexibility to use any model without needing to wait for Ollama4j to release updates for newer models.

I hope this clarifies my reasoning!

**Comment by amithkoujalgi** [comment]
> Also Timestamp in OllamaChatMessage:
> 
> The OllamaChatMessage structure should include a timestamp field. This will help models that rely on message history to determine the last or current message from the user, ensuring context is maintained across interactions.

This would certainly be helpful. I'll look into it soon.

**Comment by michaelwechner** [comment]
> Hi @michaelwechner. The "tool" role has been added by @daguava and can now be utilized as `OllamaChatMessageRole.TOOL`.
> 

Hi @amithkoujalgi thank you very much!

**Comment by amithkoujalgi** [comment]
@michaelwechner @supertick - added support for custom roles [here](https://github.com/ollama4j/ollama4j/releases/tag/1.0.86).

References to docs: 
- https://ollama4j.github.io/ollama4j/apis-generate/custom-roles
- https://ollama4j.github.io/ollama4j/apidocs/io/github/ollama4j/OllamaAPI.html#addCustomRole(java.lang.String)

Please have a look and see if this helps.

**Comment by amithkoujalgi** [comment]
> > Also Timestamp in OllamaChatMessage:
> > The OllamaChatMessage structure should include a timestamp field. This will help models that rely on message history to determine the last or current message from the user, ensuring context is maintained across interactions.
> 
> This would certainly be helpful. I'll look into it soon.

Ollama does not include any timestamps AFAIK. Do you mean that Ollama4j must include a `timestamp` field that represents the time at which the message was captured?

**Comment by daguava** [comment]
> Also Timestamp in OllamaChatMessage:
> 
> The OllamaChatMessage structure should include a timestamp field. This will help models that rely on message history to determine the last or current message from the user, ensuring context is maintained across interactions.

I'm not sure this makes sense to include in the OllamaChatMessage itself, as all information usually is provided to the model via the content of the message. Timestamp is not a standard feature in the model templating - it can be provided in the message string payload manually though. You could do things like including the timestamp in the message you put into each message object (for example "$timestamp: 'this is the message'"

I'd recommend maintaining a list of messages outside of the ollama message class itself - you could make your own message class with the ollama message being one of its members, and then all your custom info that you use associated with each message as other members.
